### ISSUE TITLE
昇腾910B上填充模式不正确

### ISSUE THREAD

**Issue by zhangxiangchn** [yeyupiaoling/VoiceprintRecognition-PaddlePaddle#14]
Traceback (most recent call last):
  File "/root/work/VoiceprintRecognition/infer_eer.py", line 88, in <module>
    eval_network(predictor, eval_list, eval_path,  sample_rate=16000)
  File "/root/work/VoiceprintRecognition/infer_eer.py", line 59, in eval_network
    embedding = predictor.predict(os.path.join(eval_path, file),sample_rate=16000)
  File "/root/work/VoiceprintRecognition/ppvector/predict.py", line 238, in predict
    audio_feature, _ = self._audio_featurizer(input_data, input_len_ratio)
  File "/usr/local/lib/python3.9/dist-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/work/VoiceprintRecognition/ppvector/data_utils/featurizer.py", line 43, in forward
    feature = self.feat_fun(waveforms)
  File "/usr/local/lib/python3.9/dist-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/work/VoiceprintRecognition/ppvector/data_utils/featurizer.py", line 94, in forward
    log_fbank = Kaldi.fbank(waveform, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/paddleaudio/compliance/kaldi.py", line 462, in fbank
    strided_input, signal_log_energy = _get_window(
  File "/usr/local/lib/python3.9/dist-packages/paddleaudio/compliance/kaldi.py", line 170, in _get_window
    offset_strided_input = paddle.nn.functional.pad(
  File "/usr/local/lib/python3.9/dist-packages/paddle/nn/functional/common.py", line 1778, in pad
    out = _C_ops.pad3d(x, pad, mode, value, data_format)
NotImplementedError: (Unimplemented) npu npu only support mode=constant right now,but received mode is replicate .
  [Hint: Expected mode == "constant", but received mode:replicate != "constant":constant.] (at /root/work/paddle_finance_qa/PaddleCustomDevice/backends/npu/kernels/pad3d_kernel.cc:43)

**Comment by yeyupiaoling** [comment]
@zhangxiangchn 这个应该是昇腾910B不支持pad3d算子的问题
